import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title:{
    "default":"Next.js 13 App CodeEvolution",
    "template":"%s | Next.js template CodeEvolution",
    "absolute":"Next.js 13 Absolute CodeEvolution",
  },
  description: "Generated by create next app",
  other: {
    google: "notranslate",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" translate="no" suppressHydrationWarning>

      <body className="notranslate" suppressHydrationWarning>
        <header
        style={{
          backgroundColor:"lightblue",
          padding:"1rem",
          // display:"flex",
          // gap:"1rem"
        }}>

          <p>Header</p>

        </header>
        {children}
        <footer
        style={{
          backgroundColor:"ghostwhite",
          padding:"1rem",
          // display:"flex",
          // gap:"1rem"
        }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
